# Generated by Django 3.1.4 on 2021-01-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_lineitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('AK', 'Ak'), ('Arunachal Pradesh', 'An'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh')], max_length=100),
        ),
    ]
