# Generated by Django 3.1.4 on 2021-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_auto_20210103_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(null=True),
        ),
    ]
